export type ServerSideShortItem = {
  sysGbCode: string;
  entpSeq: string;
  entpName: string;
  itemSeq: string;
  itemName: string;
  reportDate: string;
  slReportSeq: string;
  entpNo: string;
  reporterAddr: string;
  reporterName: string;
  ediStdCode: string;
  slOccurExpectDate: string;
  slReason: string;
  lastSupplyDate: string;
  lackQyDate: string;
  lackQy: string;
  patientMdlrtAffc: string;
  supplyPlan: string;
  supplyPlanDate: string;
  chargeName: string;
  chargeTelNo: string;
  examResultDt: string;
  reasonDocNo: string;
  deptReceiptNo: string;
};

export type ShortItem = {
  sysGbCode: string;
  entpSeq: number;
  entpName: string;
  itemSeq: number;
  itemName: string;
  reportDate: string;
  slReportSeq: string;
  entpNo: number;
  reporterAddr: string;
  reporterName: string;
  ediStdCode: string;
  slOccurExpectDate: string;
  slReason: string;
  lastSupplyDate: string;
  lackQyDate: string;
  lackQy: string;
  patientMdlrtAffc: string;
  supplyPlan: string;
  supplyPlanDate: string;
  chargeName: string;
  chargeTelNo: string;
  examResultDt: string;
  reasonDocNo: string;
  deptReceiptNo: string;
};

export type ServerSideSuspendedItem = {
  suspendReportSeq: string;
  suspendReportGb: "수입" | "생산";
  entpSeq: string;
  entpName: string;
  itemSeq: string;
  itemName: string;
  suspendDate: string;
  lackDate: string;
  reportDate: string;
  suspendReason: string;
  supplyLackPaci: string;
  supplyPlan: string;
  chargeName: string;
  chargeTel: string;
  lastSupplyDate: string;
  lastReportGb: "수입" | "생산";
  lastSupplyGb: "Y" | "N";
  suspendGb: "수입" | "생산";
  suspendYn: "Y" | "N";
};

export type SuspendedItem = {
  corpName: string;
  corpId: number;
  productId: number;
  productName: string;
  suspendedReportId: number;
  suspendedReportType: "수입" | "생산";
  reportDate: string;
  suspendedDate?: string;
  suspendedReason?: string;
  lackPossibility?: string;
  lackDate?: string;
  plan?: string;
  chargeName?: string;
  chargeTel?: string;
  lastSupplyDate?: "string";
  lastReportType?: "수입" | "생산";
  lastSupplyYN?: "Y" | "N";
  suspendedType?: "수입" | "생산";
  suspendedYn?: "Y" | "N";
};
